"""initial schema

Revision ID: 23530278c355
Revises: 006
Create Date: 2026-05-06 23:34:01.171579
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '23530278c355'
down_revision: Union[str, None] = '006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'diff',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(length=45),
               existing_nullable=True)
    op.drop_index('ix_board_collaborators_user_id', table_name='board_collaborators')
    op.alter_column('boards', 'state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('ix_boards_updated_at', table_name='boards')
    op.alter_column('capabilities', 'meta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.add_column('chat_messages', sa.Column('attachments', sa.JSON(), nullable=True))
    op.alter_column('elements', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('elements', 'meta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('elements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('elements', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_elements_board_type', table_name='elements')
    op.alter_column('governance_decisions', 'meta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('ix_governance_board_id', table_name='governance_decisions')
    op.drop_index('ix_governance_decided_at', table_name='governance_decisions')
    op.create_index(op.f('ix_governance_decisions_board_id'), 'governance_decisions', ['board_id'], unique=False)
    op.create_index(op.f('ix_governance_decisions_decided_at'), 'governance_decisions', ['decided_at'], unique=False)
    op.alter_column('import_jobs', 'result',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('import_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_import_jobs_board', table_name='import_jobs')
    op.create_index(op.f('ix_import_jobs_board_id'), 'import_jobs', ['board_id'], unique=False)
    op.alter_column('insights', 'actions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index('ix_refresh_tokens_token_hash', table_name='refresh_tokens')
    op.create_unique_constraint(None, 'refresh_tokens', ['token_hash'])
    op.alter_column('uploads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_uploads_board', table_name='uploads')
    op.create_index(op.f('ix_uploads_board_id'), 'uploads', ['board_id'], unique=False)
    op.add_column('users', sa.Column('has_seen_onboarding', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_seen_onboarding')
    op.drop_index(op.f('ix_uploads_board_id'), table_name='uploads')
    op.create_index('ix_uploads_board', 'uploads', ['board_id'], unique=False)
    op.alter_column('uploads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.create_index('ix_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=True)
    op.alter_column('insights', 'actions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('ix_import_jobs_board_id'), table_name='import_jobs')
    op.create_index('ix_import_jobs_board', 'import_jobs', ['board_id'], unique=False)
    op.alter_column('import_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('import_jobs', 'result',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_governance_decisions_decided_at'), table_name='governance_decisions')
    op.drop_index(op.f('ix_governance_decisions_board_id'), table_name='governance_decisions')
    op.create_index('ix_governance_decided_at', 'governance_decisions', ['decided_at'], unique=False)
    op.create_index('ix_governance_board_id', 'governance_decisions', ['board_id'], unique=False)
    op.alter_column('governance_decisions', 'meta',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index('ix_elements_board_type', 'elements', ['board_id', 'type'], unique=False)
    op.alter_column('elements', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('elements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('elements', 'meta',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('elements', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.drop_column('chat_messages', 'attachments')
    op.alter_column('capabilities', 'meta',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index('ix_boards_updated_at', 'boards', ['updated_at'], unique=False)
    op.alter_column('boards', 'state',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index('ix_board_collaborators_user_id', 'board_collaborators', ['user_id'], unique=False)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.String(length=45),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'diff',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
